server:
  port: 8080
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    oauth-resource:
      path: /oauth-resource/**
      url: http://localhost:6061/
    oauth:
      path: /security/**
      url: http://localhost:6060/
security:
  oauth2:
    resource:
      jwt:
        key-value: 'auth_private_key'